### ISSUE TITLE
What happened to staging branch?

### ISSUE THREAD

**Issue by marcelklehr** [studieren-ohne-grenzen/sog-ansible#23]
Git tells me my staging branch has diverged from upstream :/

**Comment by glatteis** [comment]
Isn't this a problem with your local staging branch? You probably have to merge in the changes. Or am I wrong? :D

**Comment by glatteis** [comment]
I just merged the changes from master back into staging. Feel free to revert that if that wasn't your intention.

**Comment by marcelklehr** [comment]
Yep, that was my intention. Everything works again, now. :pray:
