### ISSUE TITLE
Nextcloud deployment fails on fresh install

### ISSUE THREAD

**Issue by zonradkuse** [studieren-ohne-grenzen/sog-ansible#7]
When deploying nextcloud the path for docker-compose is not correct on CentOS7. It is not in `/usr/bin` but apparently in `/usr/local/bin/docker-compose`.

**Comment by zonradkuse** [comment]
I found more :D
`Apr 10 09:17:00 sog-de-production nginx[31502]: nginx: [emerg] open() "/etc/nginx/snippets/studieren-ohne-grenze.org.ssl.conf" failed (2: No such file or directory) in /etc/nginx/conf.d/civicrm.site.conf:54`

**Comment by marcelklehr** [comment]
Ah, sorry. I forgot the .ssl suffix. Also: There's a typo in the domain.

**Comment by zonradkuse** [comment]
I fixed the domain - that was my typo in the inventory file.

But I am afraid that your fix does not work. Nginx runs before letsencrypt, generating all config files and tries to restart. Since the ssl config is not generated yet nginx will fail at the very first deployment.

**Comment by marcelklehr** [comment]
Did you do this: https://github.com/studieren-ohne-grenzen/sog-ansible/blob/master/group_vars/sog_de/nginx.yml#L9 ?

**Comment by zonradkuse** [comment]
Ah! Nope. Is there a nicer solution to the problem involving no manual work?

**Comment by marcelklehr** [comment]
Mh. When ssl is set up, you want port 80 to redirect to 443, if not then letsencrypt needs the port for its challenges.  Might be possible to add a branch in the role somewhere.
