### ISSUE TITLE
Mattermost frontend build fails with current node version

### ISSUE THREAD

**Issue by zonradkuse** [studieren-ohne-grenzen/sog-ansible#9]
Not sure why, though...

**Comment by zonradkuse** [comment]
The problem is not nodejs but the server resources. The build takes about 1.5G memory which the small CX11 instance didn't provide with all the software installed.

**Comment by marcelklehr** [comment]
have you tried node v11?

**Comment by zonradkuse** [comment]
No but I don't think that node itself is the problem. MM uses webpack to build the frontend and process misc. That's simply resource consuming, I guess...

**Comment by zonradkuse** [comment]
I added a comment in the readme to the common pitfalls
